apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These are the shared resources that EVERY environment gets.
# The overlays (dev/prod) can add to or patch these.
resources:
  - postgres.yaml
  - backend-configmap.yaml
  - backend.yaml
  - dashboard.yaml
